### ISSUE TITLE
Enhancement request-- revoke, and delete

### ISSUE THREAD

**Issue by emoby** [winebarrel/piculet#11]
I'm an Ops Engineer in the US.  I've started to use your piculet ruby gem, and absolutely love it-- I don't know how I managed before it, THANKS for writing it!

I wanted to contribute back to the project a suggestion and code for your review and consideration.

USE CASE ONE:  We update security group IP's often, based on certain business requirements, and I found that when we need to authorize new IP's, before we revoke, we run out of rules to assign the new IP's.  I've made a single change to revoke the rules first, and authorize second.  I understand that it's not always optimal to revoke first, but I thought it might be helpful to the community to have an option to revoke first; "--revoke-first". (For our business use-case, we need to revoke first, so I've included the code changes that I put in place... obviously just changing order in your "update" method)

### ~/.rvm/gems/ruby-2.0.0-p481/gems/piculet-0.2.6/lib/piculet/wrapper/permission.rb
            def update(dsl)
              log(:info, 'Update Permission', :green, log_id)
              plus_ip_ranges, minus_ip_ranges, plus_groups, minus_groups = diff(dsl)
              unless (minus_ip_ranges + minus_groups).empty?
                @collection.revoke(protocol, port_range, (minus_ip_ranges + minus_groups), :log_color => :green)
              end
              unless (plus_ip_ranges + plus_groups).empty?
                @collection.authorize(protocol, port_range, (plus_ip_ranges + plus_groups), :log_color => :green)
              end
            end

USE CASE TWO: When a security group is deleted, most often it's attached to an object within AWS, and it can't be deleted, in which piculet stops processing the rest of the input file.  I've written a rescue block for piclulet to pass the error (as piculet currently does), and then it continues to run -- allowing the script to continue processing the rules following the error. 

## ~/.rvm/gems/ruby-2.0.0-p481/gems/piculet-0.2.6/lib/piculet/wrapper/security-group.rb
        def delete
          log(:info, 'Delete SecurityGroup', :red, "#{vpc_id || :classic} > #{name}")
          if name == 'default'
            log(:warn, 'SecurityGroup `default` is reserved', :yellow)
          else
            unless @options.dry_run
              begin
                @security_group.delete
                @options.updated = true
              rescue Exception => e
                log(:info, 'FAILED', :red, e)
              end
            end
          end
        end

Thanks again for your work with the project.​
Eric

**Comment by BackSlasher** [comment]
+1 for revoking before adding. Happens to me too (not a lot, but annoying)

**Comment by winebarrel** [comment]
Thank you for comment :smiley: 
I'll consider it.

**Comment by winebarrel** [comment]
I'm sorry that an fix is late.
[v0.2.8.beta4](https://rubygems.org/gems/piculet/versions/0.2.8.beta4) has been released.
This release includes #13.

**Comment by BackSlasher** [comment]
This can be closed now, no @winebarrel ?

**Comment by winebarrel** [comment]
Thank you for letting me know.
